# Task Configuration for EnterpriseArena
# This file contains configuration for task execution and evaluation

# Task execution settings
tasks:
  single_platform:
    timeout_seconds: 300
    max_steps: 20
    enable_retry: true
    max_retries: 3
    retry_delay: 1
    
  cross_platform:
    timeout_seconds: 600
    max_steps: 40
    enable_retry: true
    max_retries: 3
    retry_delay: 2
    
  interactive:
    timeout_seconds: 1800
    max_steps: 50
    enable_retry: false
    max_retries: 1
    retry_delay: 0

# Timeout configurations
timeouts:
  single_platform: 300
  cross_platform: 600
  interactive: 1800
  platform_connection: 30
  query_execution: 60
  action_execution: 30

# Retry configurations
retries:
  max_retries: 3
  retry_delay: 1
  exponential_backoff: true
  backoff_multiplier: 2
  max_retry_delay: 60

# Evaluation configurations
evaluation:
  enable_automatic_evaluation: true
  evaluation_timeout: 60
  metrics:
    accuracy:
      enable_exact_match: true
      enable_partial_match: true
      enable_fuzzy_match: true
      fuzzy_threshold: 0.8
    efficiency:
      enable_time_efficiency: true
      enable_step_efficiency: true
      enable_resource_efficiency: true
    error_handling:
      enable_recovery_scoring: true
      enable_graceful_degradation: true
      enable_error_communication: true
  
  # Reward calculation
  reward_weights:
    accuracy: 0.5
    efficiency: 0.3
    error_handling: 0.2
  
  # Success thresholds
  success_thresholds:
    excellent: 0.9
    good: 0.8
    fair: 0.7
    poor: 0.6

# Task categories and their specific settings
task_categories:
  lead_management:
    timeout_seconds: 180
    max_steps: 15
    expected_operations: ["query", "create", "update"]
    
  opportunity_tracking:
    timeout_seconds: 240
    max_steps: 20
    expected_operations: ["query", "create", "update", "search"]
    
  case_management:
    timeout_seconds: 200
    max_steps: 18
    expected_operations: ["query", "create", "update", "assign"]
    
  incident_management:
    timeout_seconds: 220
    max_steps: 16
    expected_operations: ["query", "create", "update", "escalate"]
    
  financial_integration:
    timeout_seconds: 400
    max_steps: 25
    expected_operations: ["query", "create", "sync", "link"]
    
  customer_service:
    timeout_seconds: 350
    max_steps: 22
    expected_operations: ["query", "create", "update", "coordinate"]

# Platform-specific task settings
platform_tasks:
  salesforce:
    default_timeout: 300
    max_query_results: 200
    enable_bulk_operations: true
    bulk_batch_size: 200
    
  servicenow:
    default_timeout: 300
    max_query_results: 100
    enable_bulk_operations: false
    bulk_batch_size: 50
    
  netsuite:
    default_timeout: 400
    max_query_results: 1000
    enable_bulk_operations: true
    bulk_batch_size: 100
    
  quickbooks:
    default_timeout: 300
    max_query_results: 500
    enable_bulk_operations: false
    bulk_batch_size: 25

# Data validation settings
validation:
  enable_input_validation: true
  enable_output_validation: true
  strict_mode: false
  allow_partial_results: true
  
# Logging and monitoring
monitoring:
  enable_performance_monitoring: true
  enable_error_tracking: true
  enable_usage_analytics: true
  log_level: "INFO"
  log_requests: true
  log_responses: false
